### ISSUE TITLE
Is Wagtail-Markdown Wagtail 4.2 compliant ? (AttributeError: 'MarkdownField' object has no attribute 'bind_to_model')

### ISSUE THREAD

**Issue by chris2fr** [torchbox/wagtail-markdown#121]
Hi,

I have the following error on compile.

There is an "AttributeError: 'MarkdownField' object has no attribute 'bind_to_model'" at the end.

There is a complaint about wagtail.core.telepath and wagtail.telepath in the ebinging.

```
/home/mannchri/wagtail/goodv/lib/python3.9/site-packages/wagtailmarkdown/widgets.py:4: RemovedInWagtail50Warning: Importing from wagtail.core.telepath is deprecated. Use wagtail.telepath instead. See https://docs.wagtail.org/en/stable/releases/3.0.html#changes-to-module-paths
  from wagtail.core.telepath import register
/home/mannchri/wagtail/goodv/lib/python3.9/site-packages/wagtailmarkdown/widgets.py:5: RemovedInWagtail50Warning: Importing from wagtail.core.widget_adapters is deprecated. Use wagtail.widget_adapters instead. See https://docs.wagtail.org/en/stable/releases/3.0.html#changes-to-module-paths
  from wagtail.core.widget_adapters import WidgetAdapter
Traceback (most recent call last):
  File "/home/mannchri/wagtail/goodv/goodv/manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
...
  File "/home/mannchri/wagtail/goodv/lib/python3.9/site-packages/wagtail/admin/panels/group.py", line 74, in <listcomp>
    self.children = [child.bind_to_model(self.model) for child in self.children]
AttributeError: 'MarkdownField' object has no attribute 'bind_to_model'

[processus terminé avec le code 1 (0x00000001)]
```

**Comment by chris2fr** [comment]
Nevermind

**Comment by zerolab** [comment]
We have an open PR #120. One way to help speed things up is if you could help review and test

**Comment by zerolab** [comment]
hmm, don't think #120 has anything to do with this 🤔

@chris2fr any chance you could share why "Nevermind"?

**Comment by zerolab** [comment]
Closing this as I've released https://github.com/torchbox/wagtail-markdown/releases/tag/v0.11.0 which I tested with Wagtail 5.0
