### ISSUE TITLE
ImportError: cannot import name 'MarkdownField'

### ISSUE THREAD

**Issue by rifuso** [torchbox/wagtail-markdown#14]
Trying to use this (mediafix branch) with the wagtail demo installation and getting this error:

```
[wagtaildemo wagtaildemo]$ ./manage.py runserver 0.0.0.0:8000
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/vagrant/.virtualenvs/wagtaildemo/lib/python3.4/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/home/vagrant/.virtualenvs/wagtaildemo/lib/python3.4/site-packages/django/core/management/__init__.py", line 312, in execute
    django.setup()
  File "/home/vagrant/.virtualenvs/wagtaildemo/lib/python3.4/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/vagrant/.virtualenvs/wagtaildemo/lib/python3.4/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/home/vagrant/.virtualenvs/wagtaildemo/lib/python3.4/site-packages/django/apps/config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/local/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/vagrant/wagtaildemo/demo/models.py", line 28, in <module>
    from wagtailmarkdown import MarkdownField, MarkdownPanel
ImportError: cannot import name 'MarkdownField'
```

On the master branch I was running into a similar issue as this:

https://github.com/torchbox/wagtail-markdown/issues/6

**Comment by tm-kn** [comment]
Added more human error in c259c093fbdb834cb66480c9c3efe78bfa066367, but please use `wagtailmarkdown.fields.MarkdownField` import from now on - on the current `master` or `mediafix`.
