### ISSUE TITLE
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.

### ISSUE THREAD

**Issue by refresher** [torchbox/wagtail-markdown#22]
I am getting this exception right after I place the 'wagtailmarkdown' in INSTALLED_APPS list in the config file.
Am I doing something wrong?

Here is the full stack trace
```
manage.py@blogtest > makemigrations
bash -cl "/opt/pydev/wtblog/env/bin/python /opt/pycharm-2016.3.2/helpers/pycharm/django_manage.py makemigrations /opt/pydev/wtblog/blogtest"
Traceback (most recent call last):
  File "/opt/pycharm-2016.3.2/helpers/pycharm/django_manage.py", line 41, in <module>
    run_module(manage_file, None, '__main__', True)
  File "/usr/lib64/python3.4/runpy.py", line 182, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib64/python3.4/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib64/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/pydev/wtblog/blogtest/manage.py", line 12, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/pydev/wtblog/env/lib64/python3.4/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/opt/pydev/wtblog/env/lib64/python3.4/site-packages/django/core/management/__init__.py", line 341, in execute
    django.setup()
  File "/opt/pydev/wtblog/env/lib64/python3.4/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/opt/pydev/wtblog/env/lib64/python3.4/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/opt/pydev/wtblog/env/lib64/python3.4/site-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/usr/lib64/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "/opt/pydev/wtblog/env/lib64/python3.4/site-packages/wagtail_markdown-0.4.1-py3.4.egg/wagtailmarkdown/__init__.py", line 16, in <module>
  File "/opt/pydev/wtblog/env/lib64/python3.4/site-packages/wagtail/wagtailcore/blocks/__init__.py", line 5, in <module>
    from .field_block import *  # NOQA
  File "/opt/pydev/wtblog/env/lib64/python3.4/site-packages/wagtail/wagtailcore/blocks/field_block.py", line 16, in <module>
    from wagtail.wagtailcore.rich_text import RichText
  File "/opt/pydev/wtblog/env/lib64/python3.4/site-packages/wagtail/wagtailcore/rich_text.py", line 10, in <module>
    from wagtail.wagtailcore.models import Page
  File "/opt/pydev/wtblog/env/lib64/python3.4/site-packages/wagtail/wagtailcore/models.py", line 9, in <module>
    from django.contrib.auth.models import Group, Permission
  File "/opt/pydev/wtblog/env/lib64/python3.4/site-packages/django/contrib/auth/models.py", line 4, in <module>
    from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
  File "/opt/pydev/wtblog/env/lib64/python3.4/site-packages/django/contrib/auth/base_user.py", line 52, in <module>
    class AbstractBaseUser(models.Model):
  File "/opt/pydev/wtblog/env/lib64/python3.4/site-packages/django/db/models/base.py", line 105, in __new__
    app_config = apps.get_containing_app_config(module)
  File "/opt/pydev/wtblog/env/lib64/python3.4/site-packages/django/apps/registry.py", line 237, in get_containing_app_config
    self.check_apps_ready()
  File "/opt/pydev/wtblog/env/lib64/python3.4/site-packages/django/apps/registry.py", line 124, in check_apps_ready
    raise AppRegistryNotReady("Apps aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.
```

```
$ pip freeze
appdirs==1.4.0
beautifulsoup4==4.5.3
bleach==1.5.0
dj-database-url==0.3.0
Django==1.10.5
django-appconf==1.0.2
django-compressor==2.1
django-libsass==0.7
django-modelcluster==3.0.1
django-redis==3.8.2
django-taggit==0.22.0
django-treebeard==4.1.0
djangorestframework==3.5.4
elasticsearch==1.2.0
html5lib==0.9999999
libsass==0.8.2
Markdown==2.6.2
olefile==0.44
packaging==16.8
Pillow==4.0.0
Pygments==2.2.0
pyparsing==2.1.10
pytz==2016.10
rcssmin==1.0.6
redis==2.10.5
requests==2.13.0
rjsmin==1.0.12
six==1.10.0
Unidecode==0.4.20
urllib3==1.19.1
wagtail==1.9
wagtail-markdown==0.4.1
webencodings==0.5
whitenoise==3.2.3
Willow==0.4
```

**Comment by refresher** [comment]
I read the other opened issues and found that issue #6 Is absolutely the same, so I checked out the __mediafix__ branch and it is working now.
