### ISSUE TITLE
Missing requirement

### ISSUE THREAD

**Issue by emorozov** [torchbox/wagtail-markdown#23]
When I install wagtail-markdown I get an error because `pyparsing` is not listed in the requirements:
```
~/work/royal_orchard$ pip install git+https://github.com/torchbox/wagtail-markdown.git
Collecting git+https://github.com/torchbox/wagtail-markdown.git
  Cloning https://github.com/torchbox/wagtail-markdown.git to /tmp/pip-oke7k_rs-build
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/jmv/.virtualenvs/rolc/lib/python3.5/site-packages/setuptools/__init__.py", line 12, in <module>
        import setuptools.version
      File "/home/jmv/.virtualenvs/rolc/lib/python3.5/site-packages/setuptools/version.py", line 1, in <module>
        import pkg_resources
      File "/home/jmv/.virtualenvs/rolc/lib/python3.5/site-packages/pkg_resources/__init__.py", line 72, in <module>
        import packaging.requirements
      File "/home/jmv/.virtualenvs/rolc/lib/python3.5/site-packages/packaging/requirements.py", line 9, in <module>
        from pyparsing import stringStart, stringEnd, originalTextFor, ParseException
    ImportError: No module named 'pyparsing'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-oke7k_rs-build/
```

Also, is it possible to upload the package to PyPI, please?

**Comment by emorozov** [comment]
Sorry, it seems that is a pip bug, not a wagtail-markdown bug.
